import fs from 'fs';

const newWords = {
  "accident": { "vi": "Tai nạn", "en": "An unfortunate incident that happens unexpectedly", "ipa": "/ˈæk.sɪ.dənt/" },
  "action": { "vi": "Hành động", "en": "The fact or process of doing something", "ipa": "/ˈæk.ʃən/" },
  "actor": { "vi": "Diễn viên", "en": "A person whose profession is acting on the stage, in movies, or on television", "ipa": "/ˈæk.tər/" },
  "advice": { "vi": "Lời khuyên", "en": "Guidance or recommendations concerning prudent future action", "ipa": "/ədˈvaɪs/" },
  "airport": { "vi": "Sân bay", "en": "A complex of runways and buildings for the takeoff, landing, and maintenance of civil aircraft", "ipa": "/ˈeə.pɔːt/" },
  "alarm": { "vi": "Báo động", "en": "An anxious awareness of danger", "ipa": "/əˈlɑːm/" },
  "album": { "vi": "Quyển album", "en": "A blank book for the insertion of photographs, stamps, or pictures", "ipa": "/ˈæl.bəm/" },
  "alcohol": { "vi": "Cồn, rượu", "en": "A colorless volatile flammable liquid", "ipa": "/ˈæl.kə.hɒl/" },
  "alien": { "vi": "Người ngoài hành tinh", "en": "Belonging to a foreign country or nation", "ipa": "/ˈeɪ.li.ən/" },
  "amount": { "vi": "Số lượng", "en": "A quantity of something", "ipa": "/əˈmaʊnt/" },
  "angel": { "vi": "Thiên thần", "en": "A spiritual being believed to act as an attendant, agent, or messenger of God", "ipa": "/ˈeɪn.dʒəl/" },
  "anger": { "vi": "Sự tức giận", "en": "A strong feeling of annoyance, displeasure, or hostility", "ipa": "/ˈæŋ.ɡər/" },
  "angle": { "vi": "Góc độ", "en": "The space (usually measured in degrees) between two intersecting lines or surfaces", "ipa": "/ˈæŋ.ɡəl/" },
  "answer": { "vi": "Câu trả lời", "en": "A thing said, written, or done to deal with or as a reaction to a question", "ipa": "/ˈɑːn.sər/" },
  "area": { "vi": "Khu vực", "en": "A region or part of a town, a country, or the world", "ipa": "/ˈeə.ri.ə/" },
  "army": { "vi": "Quân đội", "en": "An organized military force equipped for fighting on land", "ipa": "/ˈɑː.mi/" },
  "author": { "vi": "Tác giả", "en": "A writer of a book, article, or report", "ipa": "/ˈɔː.θər/" },
  "award": { "vi": "Giải thưởng", "en": "A prize or other mark of recognition given in honor of an achievement", "ipa": "/əˈwɔːd/" },
  "baby": { "vi": "Em bé", "en": "A very young child, especially one newly or recently born", "ipa": "/ˈbeɪ.bi/" },
  "back": { "vi": "Lưng", "en": "The rear surface of the human body from the shoulders to the hips", "ipa": "/bæk/" },
  "bag": { "vi": "Cái túi", "en": "A container made of flexible material with an opening at the top", "ipa": "/bæɡ/" },
  "balance": { "vi": "Sự cân bằng", "en": "An even distribution of weight enabling someone or something to remain upright and steady", "ipa": "/ˈbæl.əns/" },
  "band": { "vi": "Ban nhạc", "en": "A small group of musicians and vocalists who play pop, jazz, or rock music", "ipa": "/bænd/" },
  "bank": { "vi": "Ngân hàng", "en": "A financial establishment that invests money deposited by customers", "ipa": "/bæŋk/" },
  "base": { "vi": "Căn cứ, đáy", "en": "The lowest part or edge of something, especially the part on which it rests", "ipa": "/beɪs/" },
  "basket": { "vi": "Cái rổ", "en": "A container used to hold or carry things", "ipa": "/ˈbɑː.skɪt/" },
  "bath": { "vi": "Bồn tắm", "en": "A large container for water, used for immersing and washing the body", "ipa": "/bɑːθ/" },
  "battle": { "vi": "Trận chiến", "en": "A sustained fight between large, organized armed forces", "ipa": "/ˈbæt.əl/" },
  "beach": { "vi": "Bãi biển", "en": "A pebbly or sandy shore, especially by the ocean between high- and low-water marks", "ipa": "/biːtʃ/" },
  "beauty": { "vi": "Sắc đẹp", "en": "A combination of qualities that pleases the intellect or moral sense", "ipa": "/ˈbjuː.ti/" },
  "bed": { "vi": "Cái giường", "en": "A piece of furniture for sleep or rest", "ipa": "/bed/" },
  "beer": { "vi": "Bia", "en": "An alcoholic drink made from yeast-fermented malt flavored with hops", "ipa": "/bɪər/" },
  "bell": { "vi": "Cái chuông", "en": "A hollow object, typically made of metal and having the shape of a deep inverted cup", "ipa": "/bel/" },
  "belt": { "vi": "Thắt lưng", "en": "A strip of leather or other material worn around the waist", "ipa": "/belt/" },
  "bike": { "vi": "Xe đạp", "en": "A bicycle or motorcycle", "ipa": "/baɪk/" },
  "blood": { "vi": "Máu", "en": "The red liquid that circulates in the arteries and veins of humans and other vertebrate animals", "ipa": "/blʌd/" },
  "blow": { "vi": "Thổi", "en": "Make a current of air", "ipa": "/bləʊ/" },
  "board": { "vi": "Cái bảng", "en": "A long, thin, flat piece of wood or other hard material", "ipa": "/bɔːd/" },
  "boat": { "vi": "Cái thuyền", "en": "A small vessel for travelling over water", "ipa": "/bəʊt/" },
  "body": { "vi": "Cơ thể", "en": "The physical structure of a person or an animal", "ipa": "/ˈbɒd.i/" },
  "bomb": { "vi": "Quả bom", "en": "A container filled with explosive, incendiary material", "ipa": "/bɒm/" },
  "bone": { "vi": "Khúc xương", "en": "Any of the pieces of hard, whitish tissue making up the skeleton in humans and other vertebrates", "ipa": "/bəʊn/" },
  "book": { "vi": "Quyển sách", "en": "A written or printed work consisting of pages glued or sewn together along one side and bound in covers", "ipa": "/bʊk/" },
  "boss": { "vi": "Ông chủ", "en": "A person in charge of a worker or organization", "ipa": "/bɒs/" },
  "bottle": { "vi": "Cái chai", "en": "A glass or plastic container with a narrow neck", "ipa": "/ˈbɒt.əl/" },
  "bowl": { "vi": "Cái bát", "en": "A round, deep dish or basin used for food or liquid", "ipa": "/bəʊl/" },
  "brain": { "vi": "Bộ não", "en": "An organ of soft nervous tissue contained in the skull of vertebrates", "ipa": "/breɪn/" },
  "branch": { "vi": "Nhánh cây", "en": "A part of a tree which grows out from the trunk or from a bough", "ipa": "/brɑːntʃ/" },
  "bread": { "vi": "Bánh mì", "en": "Food made of flour, water, and yeast or another leavening agent", "ipa": "/bred/" },
  "bridge": { "vi": "Cây cầu", "en": "A structure carrying a road, path, railroad, or canal across a river, ravine, or other obstacle", "ipa": "/brɪdʒ/" },
  "brush": { "vi": "Bàn chải", "en": "An implement with a handle, consisting of bristles, hair, or wire", "ipa": "/brʌʃ/" },
  "build": { "vi": "Xây dựng", "en": "Construct by putting parts or material together over a period of time", "ipa": "/bɪld/" },
  "bus": { "vi": "Xe buýt", "en": "A large motor vehicle carrying passengers by road", "ipa": "/bʌs/" },
  "business": { "vi": "Doanh nghiệp", "en": "A person's regular occupation, profession, or trade", "ipa": "/ˈbɪz.nɪs/" },
  "butter": { "vi": "Bơ", "en": "A pale yellow edible fatty substance made by churning cream", "ipa": "/ˈbʌt.ər/" },
  "button": { "vi": "Cái nút", "en": "A small disk or knob sewn on to a garment", "ipa": "/ˈbʌt.ən/" },
  "camp": { "vi": "Trại", "en": "A place with temporary accommodations of huts, tents, or other structures", "ipa": "/kæmp/" },
  "capital": { "vi": "Thủ đô", "en": "The most important city or town of a country or region", "ipa": "/ˈkæp.ɪ.təl/" },
  "card": { "vi": "Thẻ", "en": "A piece of thick, stiff paper or thin pasteboard", "ipa": "/kɑːd/" },
  "care": { "vi": "Sự quan tâm", "en": "The provision of what is necessary for the health, welfare, maintenance, and protection of someone or something", "ipa": "/keər/" },
  "case": { "vi": "Trường hợp", "en": "An instance of a particular situation", "ipa": "/keɪs/" },
  "cash": { "vi": "Tiền mặt", "en": "Money in coins or notes", "ipa": "/kæʃ/" },
  "castle": { "vi": "Lâu đài", "en": "A large building or group of buildings fortified against attack with thick walls, battlements, towers", "ipa": "/ˈkɑː.səl/" },
  "cause": { "vi": "Nguyên nhân", "en": "A person or thing that gives rise to an action, phenomenon, or condition", "ipa": "/kɔːz/" },
  "cell": { "vi": "Tế bào", "en": "The smallest structural and functional unit of an organism", "ipa": "/sel/" },
  "center": { "vi": "Trung tâm", "en": "The middle point of a circle or sphere, equidistant from every point on the circumference or surface", "ipa": "/ˈsen.tər/" },
  "chain": { "vi": "Sợi xích", "en": "A series of linked metal rings used for fastening or securing something", "ipa": "/tʃeɪn/" },
  "chair": { "vi": "Cái ghế", "en": "A separate seat for one person, typically with a back and four legs", "ipa": "/tʃeər/" },
  "chance": { "vi": "Cơ hội", "en": "A possibility of something happening", "ipa": "/tʃɑːns/" },
  "change": { "vi": "Sự thay đổi", "en": "Make or become different", "ipa": "/tʃeɪndʒ/" },
  "character": { "vi": "Nhân vật", "en": "The mental and moral qualities distinctive to an individual", "ipa": "/ˈkær.ək.tər/" },
  "charge": { "vi": "Sạc điện", "en": "Store electrical energy in (a battery or battery-operated device)", "ipa": "/tʃɑːdʒ/" },
  "chart": { "vi": "Biểu đồ", "en": "A sheet of information in the form of a table, graph, or diagram", "ipa": "/tʃɑːt/" },
  "check": { "vi": "Kiểm tra", "en": "Examine (something) in order to determine its accuracy, quality, or condition", "ipa": "/tʃek/" },
  "child": { "vi": "Đứa trẻ", "en": "A young human being below the age of puberty or below the legal age of majority", "ipa": "/tʃaɪld/" },
  "choice": { "vi": "Sự lựa chọn", "en": "An act of selecting or making a decision when faced with two or more possibilities", "ipa": "/tʃɔɪs/" },
  "church": { "vi": "Nhà thờ", "en": "A building used for public Christian worship", "ipa": "/tʃɜːtʃ/" },
  "circle": { "vi": "Vòng tròn", "en": "A round plane figure whose boundary consists of points equidistant from a fixed point", "ipa": "/ˈsɜː.kəl/" },
  "claim": { "vi": "Lời yêu cầu", "en": "State or assert that something is the case", "ipa": "/kleɪm/" },
  "class": { "vi": "Lớp học", "en": "A set or category of things having some property or attribute in common", "ipa": "/klɑːs/" },
  "clean": { "vi": "Sạch sẽ", "en": "Free from dirt, marks, or stains", "ipa": "/kliːn/" },
  "clear": { "vi": "Rõ ràng", "en": "Easy to perceive, understand, or interpret", "ipa": "/klɪər/" },
  "clock": { "vi": "Đồng hồ", "en": "A mechanical or electrical device for measuring time, indicating hours, minutes, and sometimes seconds", "ipa": "/klɒk/" },
  "close": { "vi": "Đóng", "en": "Move or cause to move so as to cover an opening", "ipa": "/kləʊz/" },
  "cloud": { "vi": "Đám mây", "en": "A visible mass of condensed water vapor floating in the atmosphere", "ipa": "/klaʊd/" },
  "club": { "vi": "Câu lạc bộ", "en": "An association or organization dedicated to a particular interest or activity", "ipa": "/klʌb/" },
  "coach": { "vi": "Huấn luyện viên", "en": "A person who trains and directs an athlete or a sports team", "ipa": "/kəʊtʃ/" },
  "coal": { "vi": "Than đá", "en": "A combustible black or dark brown rock consisting mainly of carbonized plant matter", "ipa": "/kəʊl/" },
  "coast": { "vi": "Bờ biển", "en": "The part of the land near the sea; the edge of the land", "ipa": "/kəʊst/" },
  "coat": { "vi": "Áo khoác", "en": "An outer garment worn outdoors, having sleeves and typically extending below the hips", "ipa": "/kəʊt/" },
  "code": { "vi": "Mã số", "en": "A system of words, letters, figures, or other symbols substituted for other words", "ipa": "/kəʊd/" },
  "coffee": { "vi": "Cà phê", "en": "A hot drink made from the roasted and ground seeds of a tropical shrub", "ipa": "/ˈkɒf.i/" },
  "cold": { "vi": "Lạnh", "en": "Of or at a low or relatively low temperature", "ipa": "/kəʊld/" },
  "color": { "vi": "Màu sắc", "en": "The property possessed by an object of producing different sensations on the eye as a result of the way the object reflects or emits light", "ipa": "/ˈkʌl.ər/" },
  "company": { "vi": "Công ty", "en": "A commercial business", "ipa": "/ˈkʌm.pə.ni/" },
  "control": { "vi": "Sự điều khiển", "en": "The power to influence or direct people's behavior or the course of events", "ipa": "/kənˈtrəʊl/" },
  "cook": { "vi": "Nấu ăn", "en": "Prepare (food, a dish, or a meal) by combining and heating the ingredients in various ways", "ipa": "/kʊk/" },
  "cool": { "vi": "Mát mẻ", "en": "Of or at a fairly low temperature", "ipa": "/kuːl/" },
  "copy": { "vi": "Bản sao", "en": "A thing made to be similar or identical to another", "ipa": "/ˈkɒp.i/" },
  "corn": { "vi": "Bắp ngô", "en": "A North American cereal plant that yields large grains, or kernels, set in rows on a cob", "ipa": "/kɔːn/" },
  "corner": { "vi": "Góc", "en": "A place or angle where two or more sides or edges meet", "ipa": "/ˈkɔː.nər/" },
  "cost": { "vi": "Chi phí", "en": "Require the payment of (a specified sum of money) before it can be acquired or done", "ipa": "/kɒst/" },
  "cotton": { "vi": "Bông", "en": "A soft white fibrous substance that surrounds the seeds of a tropical and subtropical plant", "ipa": "/ˈkɒt.ən/" },
  "cough": { "vi": "Ho", "en": "Expel air from the lungs with a sudden sharp sound", "ipa": "/kɒf/" },
  "country": { "vi": "Đất nước", "en": "A nation with its own government, occupying a particular territory", "ipa": "/ˈkʌn.tri/" },
  "course": { "vi": "Khóa học", "en": "The route or direction followed by a ship, aircraft, road, or river", "ipa": "/kɔːs/" },
  "cover": { "vi": "Vỏ bọc", "en": "Put something such as a cloth or lid on top of or in front of (something)", "ipa": "/ˈkʌv.ər/" },
  "crash": { "vi": "Sự cố đâm", "en": "Collide violently with an obstacle or another vehicle", "ipa": "/kræʃ/" },
  "cream": { "vi": "Kem", "en": "The thick white or pale yellow fatty liquid which rises to the top when milk is left to stand", "ipa": "/kriːm/" },
  "crime": { "vi": "Tội phạm", "en": "An action or omission that constitutes an offense that may be prosecuted by the state and is punishable by law", "ipa": "/kraɪm/" },
  "cross": { "vi": "Cây thánh giá", "en": "A mark, object, or figure formed by two short intersecting lines or pieces", "ipa": "/krɒs/" },
  "crowd": { "vi": "Đám đông", "en": "A large number of people gathered together in a disorganized or unruly way", "ipa": "/kraʊd/" },
  "crown": { "vi": "Vương miện", "en": "A circular ornamental headdress worn by a monarch as a symbol of authority", "ipa": "/kraʊn/" },
  "cry": { "vi": "Khóc", "en": "Shed tears, typically as an expression of distress, pain, or sorrow", "ipa": "/kraɪ/" },
  "culture": { "vi": "Văn hóa", "en": "The arts and other manifestations of human intellectual achievement regarded collectively", "ipa": "/ˈkʌl.tʃər/" },
  "cure": { "vi": "Chữa bệnh", "en": "Relieve (a person or animal) of the symptoms of a disease or condition", "ipa": "/kjʊər/" },
  "curve": { "vi": "Đường cong", "en": "A line or outline which gradually deviates from being straight for some or all of its length", "ipa": "/kɜːv/" },
  "damage": { "vi": "Sự hư hại", "en": "Physical harm caused to something in such a way as to impair its value, usefulness, or normal function", "ipa": "/ˈdæm.ɪdʒ/" },
  "danger": { "vi": "Mối nguy hiểm", "en": "The possibility of suffering harm or injury", "ipa": "/ˈdeɪn.dʒər/" },
  "degree": { "vi": "Mức độ", "en": "The amount, level, or extent to which something happens or is present", "ipa": "/dɪˈɡriː/" },
  "design": { "vi": "Thiết kế", "en": "A plan or drawing produced to show the look and function or workings of a building", "ipa": "/dɪˈzaɪn/" },
  "detail": { "vi": "Chi tiết", "en": "An individual feature, fact, or item", "ipa": "/ˈdiː.teɪl/" },
  "device": { "vi": "Thiết bị", "en": "A thing made or adapted for a particular purpose", "ipa": "/dɪˈvaɪs/" },
  "diamond": { "vi": "Kim cương", "en": "A precious stone consisting of a clear and typically colorless crystalline form of pure carbon", "ipa": "/ˈdaɪə.mənd/" },
  "diet": { "vi": "Chế độ ăn", "en": "The kinds of food that a person, animal, or community habitually eats", "ipa": "/ˈdaɪ.ət/" },
  "disease": { "vi": "Căn bệnh", "en": "A disorder of structure or function in a human, animal, or plant", "ipa": "/dɪˈziːz/" },
  "distance": { "vi": "Khoảng cách", "en": "An amount of space between two things or people", "ipa": "/ˈdɪs.təns/" },
  "doctor": { "vi": "Bác sĩ", "en": "A qualified practitioner of medicine; a physician", "ipa": "/ˈdɒk.tər/" },
  "dream": { "vi": "Giấc mơ", "en": "A series of thoughts, images, and sensations occurring in a person's mind during sleep", "ipa": "/driːm/" },
  "dress": { "vi": "Cái váy", "en": "A one-piece garment for a woman or girl that covers the body and extends down over the legs", "ipa": "/dres/" },
  "drink": { "vi": "Đồ uống", "en": "Take a liquid into the mouth and swallow", "ipa": "/drɪŋk/" },
  "drive": { "vi": "Lái xe", "en": "Operate and control the direction and speed of a motor vehicle", "ipa": "/draɪv/" },
  "drop": { "vi": "Giọt", "en": "Let or make (something) fall vertically", "ipa": "/drɒp/" },
  "dust": { "vi": "Bụi", "en": "Fine, dry powder consisting of tiny particles of earth or waste matter", "ipa": "/dʌst/" },
  "earth": { "vi": "Trái đất", "en": "The planet on which we live; the world", "ipa": "/ɜːθ/" },
  "edge": { "vi": "Cạnh", "en": "The outside limit of an object, area, or surface", "ipa": "/edʒ/" },
  "effect": { "vi": "Hiệu ứng", "en": "A change which is a result or consequence of an action or other cause", "ipa": "/ɪˈfekt/" },
  "effort": { "vi": "Sự nỗ lực", "en": "A vigorous or determined attempt", "ipa": "/ˈef.ət/" },
  "energy": { "vi": "Năng lượng", "en": "The strength and vitality required for sustained physical or mental activity", "ipa": "/ˈen.ə.dʒi/" },
  "engine": { "vi": "Động cơ", "en": "A machine with moving parts that converts power into motion", "ipa": "/ˈen.dʒɪn/" },
  "event": { "vi": "Sự kiện", "en": "A thing that happens, especially one of importance", "ipa": "/ɪˈvent/" },
  "expert": { "vi": "Chuyên gia", "en": "A person who has a comprehensive and authoritative knowledge of or skill in a particular area", "ipa": "/ˈek.spɜːt/" },
  "fact": { "vi": "Sự thật", "en": "A thing that is indisputably the case", "ipa": "/fækt/" },
  "factor": { "vi": "Yếu tố", "en": "A circumstance, fact, or influence that contributes to a result or outcome", "ipa": "/ˈfæk.tər/" },
  "factory": { "vi": "Nhà máy", "en": "A building or group of buildings where goods are manufactured or assembled chiefly by machine", "ipa": "/ˈfæk.tər.i/" },
  "family": { "vi": "Gia đình", "en": "A group of one or more parents and their children living together as a unit", "ipa": "/ˈfæm.əl.i/" },
  "farm": { "vi": "Nông trại", "en": "An area of land and its buildings used for growing crops and rearing animals", "ipa": "/fɑːm/" },
  "farmer": { "vi": "Nông dân", "en": "A person who owns or manages a farm", "ipa": "/ˈfɑː.mər/" },
  "father": { "vi": "Bố", "en": "A man in relation to his natural child or children", "ipa": "/ˈfɑː.ðər/" },
  "fear": { "vi": "Nỗi sợ", "en": "An unpleasant emotion caused by the belief that someone or something is dangerous", "ipa": "/fɪər/" },
  "field": { "vi": "Cánh đồng", "en": "An area of open land, especially one planted with crops or pasture", "ipa": "/fiːld/" },
  "fight": { "vi": "Cuộc chiến", "en": "Take part in a violent struggle involving the exchange of physical blows or the use of weapons", "ipa": "/faɪt/" },
  "figure": { "vi": "Hình dáng", "en": "A number, especially one which forms part of official statistics", "ipa": "/ˈfɪɡ.ər/" },
  "film": { "vi": "Bộ phim", "en": "A story or event recorded by a camera as a set of moving images", "ipa": "/fɪlm/" },
  "finger": { "vi": "Ngón tay", "en": "Each of the four slender jointed parts attached to either hand", "ipa": "/ˈfɪŋ.ɡər/" },
  "floor": { "vi": "Sàn nhà", "en": "The lower surface of a room, on which one may walk", "ipa": "/flɔːr/" },
  "focus": { "vi": "Trọng tâm", "en": "The center of interest or activity", "ipa": "/ˈfəʊ.kəs/" },
  "food": { "vi": "Thức ăn", "en": "Any nutritious substance that people or animals eat or drink", "ipa": "/fuːd/" },
  "foot": { "vi": "Bàn chân", "en": "The lower extremity of the leg below the ankle", "ipa": "/fʊt/" },
  "force": { "vi": "Lực lượng", "en": "Strength or energy as an attribute of physical action or movement", "ipa": "/fɔːs/" },
  "form": { "vi": "Hình thức", "en": "The visible shape or configuration of something", "ipa": "/fɔːm/" },
  "friend": { "vi": "Bạn bè", "en": "A person whom one knows and with whom one has a bond of mutual affection", "ipa": "/frend/" },
  "front": { "vi": "Phía trước", "en": "The side or part of an object that presents itself to view", "ipa": "/frʌnt/" },
  "fruit": { "vi": "Trái cây", "en": "The sweet and fleshy product of a tree or other plant that contains seed and can be eaten", "ipa": "/fruːt/" },
  "future": { "vi": "Tương lai", "en": "The time or a period of time following the moment of speaking or writing", "ipa": "/ˈfjuː.tʃər/" },
  "game": { "vi": "Trò chơi", "en": "A form of play or sport, especially a competitive one", "ipa": "/ɡeɪm/" },
  "garden": { "vi": "Khu vườn", "en": "A piece of ground, often near a house, used for growing flowers, fruit, or vegetables", "ipa": "/ˈɡɑː.dən/" },
  "gas": { "vi": "Khí gas", "en": "A substance or matter in a state in which it will expand freely to fill the whole of a container", "ipa": "/ɡæs/" },
  "gate": { "vi": "Cánh cổng", "en": "A hinged barrier used to close an opening in a wall, fence, or hedge", "ipa": "/ɡeɪt/" },
  "gift": { "vi": "Món quà", "en": "A thing given willingly to someone without payment", "ipa": "/ɡɪft/" },
  "glass": { "vi": "Thủy tinh", "en": "A hard, brittle substance, typically transparent or translucent", "ipa": "/ɡlɑːs/" },
  "goal": { "vi": "Mục tiêu", "en": "The object of a person's ambition or effort; an aim or desired result", "ipa": "/ɡəʊl/" },
  "gold": { "vi": "Vàng", "en": "A yellow precious metal, the chemical element of atomic number 79", "ipa": "/ɡəʊld/" },
  "group": { "vi": "Nhóm", "en": "A number of people or things that are located close together or are considered or classed together", "ipa": "/ɡruːp/" },
  "guest": { "vi": "Khách", "en": "A person who is invited to visit the home of or take part in a function organized by another", "ipa": "/ɡest/" },
  "guide": { "vi": "Hướng dẫn", "en": "A person who advises or shows the way to others", "ipa": "/ɡaɪd/" },
  "hair": { "vi": "Tóc", "en": "Any of the fine threadlike strands growing from the skin of humans, mammals, and some other animals", "ipa": "/heər/" },
  "half": { "vi": "Một nửa", "en": "Either of two equal or corresponding parts into which something is or can be divided", "ipa": "/hɑːf/" },
  "hall": { "vi": "Hội trường", "en": "An area in a building onto which rooms open; a corridor", "ipa": "/hɔːl/" },
  "hand": { "vi": "Bàn tay", "en": "The end part of a person's arm beyond the wrist, including the palm, fingers, and thumb", "ipa": "/hænd/" },
  "head": { "vi": "Cái đầu", "en": "The upper part of the human body, or the front or upper part of the body of an animal", "ipa": "/hed/" },
  "health": { "vi": "Sức khỏe", "en": "The state of being free from illness or injury", "ipa": "/helθ/" },
  "heart": { "vi": "Trái tim", "en": "A hollow muscular organ that pumps the blood through the circulatory system", "ipa": "/hɑːt/" },
  "heat": { "vi": "Hơi nóng", "en": "The quality of being hot; high temperature", "ipa": "/hiːt/" },
  "history": { "vi": "Lịch sử", "en": "The study of past events, particularly in human affairs", "ipa": "/ˈhɪs.tər.i/" },
  "hole": { "vi": "Cái lỗ", "en": "A hollow place in a solid body or surface", "ipa": "/həʊl/" },
  "home": { "vi": "Ngôi nhà", "en": "The place where one lives permanently, especially as a member of a family or household", "ipa": "/həʊm/" },
  "hope": { "vi": "Hy vọng", "en": "A feeling of expectation and desire for a certain thing to happen", "ipa": "/həʊp/" },
  "horse": { "vi": "Con ngựa", "en": "A solid-hoofed plant-eating domesticated mammal", "ipa": "/hɔːs/" },
  "hospital": { "vi": "Bệnh viện", "en": "An institution providing medical and surgical treatment and nursing care for sick or injured people", "ipa": "/ˈhɒs.pɪ.təl/" },
  "hotel": { "vi": "Khách sạn", "en": "An establishment providing accommodations, meals, and other services for travelers and tourists", "ipa": "/həʊˈtel/" },
  "hour": { "vi": "Giờ", "en": "A period of time equal to a twenty-fourth part of a day and night and divided into 60 minutes", "ipa": "/aʊər/" },
  "house": { "vi": "Ngôi nhà", "en": "A building for human habitation, especially one that is lived in by a family or small group of people", "ipa": "/haʊs/" },
  "idea": { "vi": "Ý tưởng", "en": "A thought or suggestion as to a possible course of action", "ipa": "/aɪˈdɪə/" },
  "image": { "vi": "Hình ảnh", "en": "A representation of the external form of a person or thing in art", "ipa": "/ˈɪm.ɪdʒ/" },
  "impact": { "vi": "Sự tác động", "en": "The action of one object coming forcibly into contact with another", "ipa": "/ˈɪm.pækt/" },
  "income": { "vi": "Thu nhập", "en": "Money received, especially on a regular basis, for work or through investments", "ipa": "/ˈɪn.kʌm/" },
  "industry": { "vi": "Công nghiệp", "en": "Economic activity concerned with the processing of raw materials and manufacture of goods", "ipa": "/ˈɪn.də.stri/" },
  "information": { "vi": "Thông tin", "en": "Facts provided or learned about something or someone", "ipa": "/ˌɪn.fəˈmeɪ.ʃən/" },
  "insect": { "vi": "Côn trùng", "en": "A small arthropod animal that has six legs and generally one or two pairs of wings", "ipa": "/ˈɪn.sekt/" },
  "interest": { "vi": "Sự quan tâm", "en": "The state of wanting to know or learn about something or someone", "ipa": "/ˈɪn.trəst/" },
  "internet": { "vi": "Mạng internet", "en": "A global computer network providing a variety of information and communication facilities", "ipa": "/ˈɪn.tə.net/" },
  "island": { "vi": "Hòn đảo", "en": "A piece of land surrounded by water", "ipa": "/ˈaɪ.lənd/" },
  "issue": { "vi": "Vấn đề", "en": "An important topic or problem for debate or discussion", "ipa": "/ˈɪʃ.uː/" }
};

const dictPath = './src/data/dictionary.json';
const dict = JSON.parse(fs.readFileSync(dictPath, 'utf8'));

Object.assign(dict, newWords);

fs.writeFileSync(dictPath, JSON.stringify(dict, null, 2), 'utf8');
console.log(`Added ${Object.keys(newWords).length} words. Total: ${Object.keys(dict).length}`);
